Reoganize CMake workflow.

diff --git a/.github/workflows/AoC_CMake_Linux.yml b/.github/workflows/AoC_CMake_Linux.yml
--- a/.github/workflows/AoC_CMake_Linux.yml
+++ b/.github/workflows/AoC_CMake_Linux.yml
@@ -1,4 +1,4 @@
-name: AoC CMake C++ Part - Linux
+name: AoC CMake C++ Part
 
 on:
   push:
@@ -9,13 +9,13 @@ on:
 env:
   BUILD_TYPE: Release
   BUILD_DIR: build
+  INSTALL_PREFIX: build/install
 
 jobs:
   downloadInput:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
@@ -24,9 +24,7 @@ jobs:
         with:
           python-version: "3.x"
 
-      - name: Install Python dependencies
-        run: |
-          tree
+      - run: |
           python -m pip install --upgrade pip
           pip install -r InputDownloader/requirements.txt
 
@@ -44,11 +42,20 @@ jobs:
             ./**/input.txt
 
   build:
-    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+        include:
+          - os: ubuntu-latest
+            preset: "unix-release"
+          - os: windows-latest
+            preset: "windows-gcc-release"
+
+    runs-on: ${{ matrix.os }}
     needs: downloadInput
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
@@ -59,60 +66,84 @@ jobs:
           path: |
             ./
 
-      # - name: Cache CMake build files
-      #   id: cache-cmake
+      # - name: Restore CMake build files
       #   uses: actions/cache@v4
       #   with:
-      #     path: |
-      #       ${{ env.BUILD_DIR }}
-      #     key: cmake-${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/*.h') }}
+      #     path: ${{ env.BUILD_DIR }}
+      #     key: cmake-${{ matrix.os }}-${{ matrix.preset }}-${{ hashFiles('**/*.cpp **/*.h') }}
 
       - name: Configure CMake
-        if: steps.cache-cmake.outputs.cache-hit != 'true'
+        # if: steps.cache-cmake.outputs.cache-hit != 'true'
+        id: cmake-configure
         run: |
-          tree
-          cmake -S . -B ${{ env.BUILD_DIR }} -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
+          cmake --list-presets
+          cmake --preset=${{ matrix.preset }}
+
+      - if: ${{ failure() }}
+        run: |
+          cmake --preset=default
 
       - name: Build project
-        if: steps.cache-cmake.outputs.cache-hit != 'true'
+        # if: steps.cache-cmake.outputs.cache-hit != 'true'
         run: |
-          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}
+          cmake --build --preset=${{ matrix.preset }}
+
+      - name: Install binary
+        run: |
+          cmake --install ${{ env.BUILD_DIR }}/${{ matrix.preset }} --prefix=${{ env.INSTALL_PREFIX }}
+
+      # - name: Cache CMake build files
+      #   if: steps.cache-cmake.outputs.cache-hit != 'true'
+      #   uses: actions/cache@v4
+      #   with:
+      #     path: ${{ env.BUILD_DIR }}
+      #     key: cmake-${{ matrix.os }}-${{ matrix.preset }}-${{ hashFiles('**/*.cpp' '**/*.h') }}
 
       - name: Upload binary
         uses: actions/upload-artifact@v4
         with:
-          name: BINARY
+          name: BINARY-${{ matrix.os }}
           path: |
             **/res.log
-            ${{ env.BUILD_DIR }}
+            ${{ env.INSTALL_PREFIX }}
 
   run:
-    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+        year: [2024]
+    runs-on: ${{ matrix.os }}
     needs: build
     steps:
       - name: Download binary
         uses: actions/download-artifact@v4
         with:
-          name: BINARY
+          name: BINARY-${{ matrix.os }}
           path: |
             .
 
-      - name: Check binary
-        run: |
-          tree
-
-      - name: Run tests (Linux) Generate results log files
-        working-directory: ${{ env.BUILD_DIR }}/2024
+      - name: Generate results log files (linux)
+        if: ${{ matrix.os == 'ubuntu-latest' }}
+        working-directory: ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}
         shell: bash
         run: |
           chmod u+x ./solution
-          ./solution 1>actionRes.log 2>runtime.log 
-          cat actionRes.log
-          cat runtime.log
+          ./solution 1>actionRes.log 2>runtime.log
 
-      - name: Diff files and fail if different
+      - name: Generate results log files (windows)
+        if: ${{ matrix.os == 'windows-latest' }}
+        working-directory: ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}
+        shell: cmd
         run: |
-          if ! diff -u ${{ env.BUILD_DIR }}/2024/actionRes.log ./2024/res.log > diff.log; then
+          .\solution 1>actionRes.log 2>runtime.log 
+          type actionRes.log
+          type runtime.log
+
+      - name: Diff files
+        shell: bash
+        run: |
+          if ! diff -u ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}/actionRes.log ${{ matrix.year }}/res.log > diff.log; then
             echo "::error::Files differ. See diff.log for details."
             cat diff.log
             exit 1
@@ -124,31 +155,15 @@ jobs:
         if: ${{ failure() }}
         uses: actions/upload-artifact@v4
         with:
-          name: build-output-${{ runner.os }}
+          name: run-failure-${{ matrix.os }}-${{ matrix.year }}
           path: |
-            ${{ env.BUILD_DIR }}/
             diff.log
 
-      - name: Upload runtime results
-        uses: actions/upload-artifact@v4
-        with:
-          name: run-output
-          path: |
-            ./${{ env.BUILD_DIR }}/2024/runtime.log
-
-  LogResults:
-    runs-on: ubuntu-latest
-    needs: run
-    steps:
-      - name: Download binary
-        uses: actions/download-artifact@v4
-        with:
-          name: run-output
-          path: |
-            ./
-
-      - name: Print log
+      - name: LogResults
+        shell: bash
+        working-directory: ${{ env.INSTALL_PREFIX }}/AoC/${{ matrix.year }}
         run: |
+          cat actionRes.log
           cat runtime.log
 
   report-if-diff-fail:
@@ -156,13 +171,5 @@ jobs:
     needs: run
     if: ${{ failure() }}
     steps:
-      - name: Download binary
-        uses: actions/download-artifact@v4
-        with:
-          name: build-output-${{ runner.os }}
-          path: |
-            ./
-
-      - name: Upload artifacts on failure
-        run: |
-          cat diff.log
+      - run: |
+          echo "FAILED"
